#!/bin/bash
set +e

LOG=/var/log/foreman-selinux-install.log

for selinuxvariant in targeted
do
  if /usr/sbin/semodule -s $selinuxvariant -l >/dev/null; then
    # Load policy
    /usr/sbin/semanage module -S $selinuxvariant \
      -a /usr/share/selinux/${selinuxvariant}/crane.pp.bz2

    # Append to log file
    echo "$(date) $0" >> $LOG
  fi
done
