#!/bin/bash
set +e

TMP=$(mktemp -t katello-selinux-enable.XXXXXXXXXX)
trap "rm -rf '$TMP'" EXIT INT TERM

for selinuxvariant in targeted
do
  if /usr/sbin/semodule -s $selinuxvariant -l >/dev/null; then
    # Load policy
    /usr/sbin/semanage module -S $selinuxvariant \
      -a /usr/share/selinux/${selinuxvariant}/katello.pp.bz2

    /usr/sbin/semanage -S $selinuxvariant -i $TMP
  fi
done
