#!/bin/bash
set +e

TMP=$(mktemp -t katello-selinux-enable.XXXXXXXXXX)
trap "rm -rf '$TMP'" EXIT INT TERM

for selinuxvariant in targeted
do
  if /usr/sbin/semodule -s $selinuxvariant -l >/dev/null; then
    # Load policy
    /usr/sbin/semanage module -S $selinuxvariant \
      -a /usr/share/selinux/${selinuxvariant}/katello.pp.bz2

    # Remove previously defined elasticsearch_port_t
    # (this can be removed in future release)
    /usr/sbin/semanage port -E | \
      grep elasticsearch_port_t | \
      sed s/-a/-d/g | \
      /usr/sbin/semanage -S $selinuxvariant -i -

    /usr/sbin/semanage -S $selinuxvariant -i $TMP
  fi
done
